name: StackRox on Minikube Test

on: [push, pull_request]

jobs:
  stackrox-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Runner Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          df -h
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          cpus: 2
          memory: 5000mb
          driver: docker
    
      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Setup StackRox Central
        run: |
          helm repo add stackrox https://raw.githubusercontent.com/stackrox/helm-charts/main/opensource/
          helm repo update
      
      - name: Deploy StackRox Central
        run: |
          helm upgrade --install -n stackrox --create-namespace stackrox-central-services \
          stackrox/stackrox-central-services \
          --set central.adminPassword.value="helloworld" \
          --set central.persistence.none="true" \
          --set central.resources.requests.memory=1Gi \
          --set central.resources.requests.cpu=1 \
          --set central.resources.limits.memory=2Gi \
          --set central.resources.limits.cpu=1 \
          --set central.db.resources.requests.memory=1Gi \
          --set central.db.resources.requests.cpu=500m \
          --set central.db.resources.limits.memory=2Gi \
          --set central.db.resources.limits.cpu=1 \
          --set scanner.autoscaling.disable=true \
          --set scanner.replicas=1 \
          --set scanner.resources.requests.memory=500Mi \
          --set scanner.resources.requests.cpu=500m \
          --set scanner.resources.limits.memory=2500Mi \
          --set scanner.resources.limits.cpu=2000m

      - name: Wait for StackRox Central rollout
        run: |
          echo "Waiting for Central deployments to be available..."
          kubectl rollout status deployment/central -n stackrox --timeout=10m
          kubectl rollout status deployment/central-db -n stackrox --timeout=10m
          kubectl rollout status deployment/scanner -n stackrox --timeout=10m
          kubectl rollout status deployment/scanner-db -n stackrox --timeout=10m
          echo "All Central deployments are available!"
      
      - name: Check StackRox Central status
        run: |
          kubectl get pods -n stackrox
          kubectl get services -n stackrox
          kubectl get deployments -n stackrox
          kubectl get statefulsets -n stackrox
          kubectl get all -n stackrox
      
      - name: Scan a test image
        run: |
          kubectl run -n stackrox test-scan --image=alpine:latest -- sleep 3600
          sleep 30
          kubectl logs -n stackrox -l app=scanner -c scanner | grep "Scan completed for image alpine:latest"
